apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: megatron-pytorchjob
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      template:
        metadata:
          labels:
            name: megatron-pytorchjob
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
          - name: pytorch
            image: nvcr.io/nvidia/pytorch:23.06-py3
            imagePullPolicy: IfNotPresent
            command:
            - "/bin/bash"
            - "-c"
            - "cd /mnt/pvc/coreweave-megatron && ./pretrain_multi_node.sh --save-to-pvc" # add --save-to-pvc to save checkpoints to pvc
            tty: true
            env:
            - name: NCCL_DEBUG
              value: "INFO"
            - name: GPUS_PER_NODE
              value: "1"
            - name: TP_SIZE
              value: "1"
            - name: PP_SIZE
              value: "2"
            # Model Config, you can find values here: https://arxiv.org/pdf/2005.14165.pdf
            - name: N_LAYERS
              value: "32"
            - name: D_MODEL
              value: "4096"
            - name: N_HEADS
              value: "32"
            - name: M_BS
              value: "1"
            - name: G_BS
              value: "1"
            securityContext:
              runAsUser: 0
            volumeMounts:
              - name: megatron-dev
                mountPath: /mnt/pvc
              - name: dshm
                mountPath: /dev/shm
              - name: checkpoint-dir
                mountPath: /mnt/checkpoint
            resources:
              requests:
                cpu: 16
                memory: 128Gi
                nvidia.com/gpu: 1
              limits:
                cpu: 16
                memory: 128Gi 
                nvidia.com/gpu: 1
          volumes:
            - name: megatron-dev
              persistentVolumeClaim:
                claimName: megatron-dev
            - emptyDir:
                medium: Memory
              name: dshm
            - emptyDir:
                medium: Memory
              name: checkpoint-dir
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values: 
                    - LAS1
                  - key: gpu.nvidia.com/class
                    operator: In
                    values:
                    - RTX_A6000
          restartPolicy: Never
    Worker:
      replicas: 1
      template:
        metadata:
          labels:
            name: megatron-pytorchjob
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
          - name: pytorch
            image: nvcr.io/nvidia/pytorch:23.06-py3
            imagePullPolicy: IfNotPresent
            command:
            - "/bin/bash"
            - "-c"
            - "cd /mnt/pvc/coreweave-megatron && ./pretrain_multi_node.sh --save-to-pvc" # add --save-to-pvc to save checkpoints to pvc
            tty: true
            env:
            - name: NCCL_DEBUG
              value: "INFO"
            - name: GPUS_PER_NODE
              value: "1"
            - name: TP_SIZE
              value: "1"
            - name: PP_SIZE
              value: "2"
            # Model Config, you can find values here: https://arxiv.org/pdf/2005.14165.pdf
            - name: N_LAYERS
              value: "32"
            - name: D_MODEL
              value: "4096"
            - name: N_HEADS
              value: "32"
            - name: M_BS
              value: "1"
            - name: G_BS
              value: "1"
            securityContext:
              runAsUser: 0
            volumeMounts:
              - name: megatron-dev
                mountPath: /mnt/pvc
              - name: dshm
                mountPath: /dev/shm
              - name: checkpoint-dir
                mountPath: /mnt/checkpoint
            resources:
              requests:
                cpu: 16
                memory: 128Gi
                nvidia.com/gpu: 1
              limits:
                cpu: 16
                memory: 128Gi 
                nvidia.com/gpu: 1
          volumes:
            - name: megatron-dev
              persistentVolumeClaim:
                claimName: megatron-dev
            - emptyDir:
                medium: Memory
              name: dshm
            - emptyDir:
                medium: Memory
              name: checkpoint-dir
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values: 
                    - LAS1
                  - key: gpu.nvidia.com/class
                    operator: In
                    values:
                    - RTX_A6000
          restartPolicy: Never
