apiVersion: batch/v1
kind: Job
metadata:
  name: megatron-train-job-single-node
spec:
  template:
    spec:
      containers:
      - name: megatron-train
        image: nvcr.io/nvidia/pytorch:23.06-py3
        imagePullPolicy: IfNotPresent
        command: ["bash", "-c", "cd /mnt/pvc/coreweave-megatron && ./pretrain_single_node.sh"]
        tty: true
        securityContext:
          runAsUser: 0
        volumeMounts:
          - name: megatron-dev
            mountPath: /mnt/pvc
          - name: dshm
            mountPath: /dev/shm
        resources:
          requests:
            cpu: 32
            memory: 512Gi
            nvidia.com/gpu: 8
          limits:
            cpu: 32
            memory: 512Gi 
            nvidia.com/gpu: 8
      volumes:
        - name: megatron-dev
          persistentVolumeClaim:
            claimName: megatron-dev
        - emptyDir:
            medium: Memory
          name: dshm
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values: 
                - LAS1
              - key: gpu.nvidia.com/class
                operator: In
                values:
                - A40
      restartPolicy: Never
  backoffLimit: 2