apiVersion: apps/v1
kind: Deployment
metadata:
  name: megatron-ssh
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: megatron-ssh
  template:
    metadata:
      labels:
        app.kubernetes.io/name: megatron-ssh
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: sshd
          command: [ "/bin/bash", "-c" ]
          args:
            - |
              apt-get -qq update && \
              DEBIAN_FRONTEND=noninteractive \
                apt-get -qq install --no-install-recommends -y \
                ssh ca-certificates tini bash \
                libncurses5 curl wget sudo htop git rsync locales \
                tmux unzip nano vim apt-utils iputils-ping && \
              apt-get clean && \
              locale-gen en_US.UTF-8 && \
              rm /etc/ssh/ssh_host_* && \
              \
              install -d --mode=0755 --owner=0 --group=0 /var/run/sshd && \
              install -d --mode=0700 --owner=0 --group=0 /root/.ssh && \
              install --mode=600 --owner=0 --group=0 /dev/null /etc/ssh/sshd_config.d/10-key-auth.conf && \
              echo "PasswordAuthentication no" >> /etc/ssh/sshd_config.d/10-key-auth.conf && \
              echo "PermitRootLogin without-password" >> /etc/ssh/sshd_config.d/10-key-auth.conf && \
              sed -i -E -e \
                's:session(\s*)required(\s*)pam_loginuid\.so:session\1optional\2pam_loginuid.so:g' \
                /etc/pam.d/sshd && \
              echo 'Set disable_coredump false' >> /etc/sudo.conf && \
              \
              ln -s /etc/ssh/host_config/ssh_host_ed25519_key /etc/ssh/ssh_host_ed25519_key
              install --mode=600 --owner=0 --group=0 /etc/ssh/host_config/authorized_keys /root/.ssh/authorized_keys && \
              ssh-keygen -f /etc/ssh/ssh_host_ed25519_key -y > /etc/ssh/ssh_host_ed25519_key.pub && \
              \
              exec /usr/bin/tini -- service ssh start -D
          tty: true
          image: nvcr.io/nvidia/pytorch:23.06-py3
          ports:
            - name: sshd
              containerPort: 22
              protocol: TCP
          volumeMounts:
            - name: megatron-dev
              mountPath: /mnt/pvc
            - name: ssh-host-config
              mountPath: "/etc/ssh/host_config"
              readOnly: true
            - name: dshm
              mountPath: /dev/shm
            - name: run-lock
              mountPath: /run/lock

          resources:
            requests:
              cpu: 32
              memory: 512Gi
            limits:
              cpu: 32
              memory: 512Gi
              nvidia.com/gpu: 8
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: gpu.nvidia.com/class
                    operator: In
                    values:
                      - A40
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                      - LAS1

      volumes:
        - name: ssh-host-config
          secret:
            secretName: ssh-host-config
            defaultMode: 0600
        - name: run-lock
          emptyDir:
            medium: Memory
        - name: megatron-dev
          persistentVolumeClaim:
            claimName: megatron-dev
        - name: dshm
          emptyDir:
            medium: Memory
      restartPolicy: Always
